### ISSUE TITLE
State of store can change before the provider subscribes

### ISSUE THREAD

**Issue by joshjg** [epeli/redux-hooks#7]
Currently, there is a timing issue when children dispatch an action inside `useEffect` during their first render.
Here's the order of events:
1. Some consumer reads the initial value via `useMapState`
2. A child of the provider dispatches an action inside `useEffect`
3. The provider itself subscribes to the store via `useEffect`

As a result, consumers are not updated with the new state value. Here's how react-redux handles this:
https://github.com/reduxjs/react-redux/blob/72ed6db1947913bdd4900b324243c43a490b4c5a/src/components/Provider.js#L56

**Comment by esamattis** [comment]
Thanks for bringing this up. Will look into it.

**Comment by esamattis** [comment]
Fix released in v0.5.4
